services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-instance
    volumes:
      - ../:/cloud
    working_dir: /cloud
    command: /bin/bash
    env_file:
      - ../dev.env

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack Gateway port - default for all services
      - "4571:4571" # LocalStack SQS port, it could be a range like "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs # Specify the services you want to run
      - DEBUG=1
    volumes:
      - ./localstack:/tmp/localstack